core/routes/admin.php
<?php

core/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/cron-price', 'FrontendController@cronPrice');

//Payment IPN

Route::get('/ipnbtc', 'PaymentController@ipnBchain')->name('ipn.bchain');
Route::get('/ipnblockbtc', 'PaymentController@blockIpnBtc')->name('ipn.block.btc');
Route::get('/ipnblocklite', 'PaymentController@blockIpnLite')->name('ipn.block.lite');
Route::get('/ipnblockdog', 'PaymentController@blockIpnDog')->name('ipn.block.dog');
Route::post('/ipnpaypal', 'PaymentController@ipnpaypal')->name('ipn.paypal');
Route::post('/ipnperfect', 'PaymentController@ipnperfect')->name('ipn.perfect');
Route::post('/ipnstripe', 'PaymentController@ipnstripe')->name('ipn.stripe');
Route::post('/ipnskrill', 'PaymentController@skrillIPN')->name('ipn.skrill');
Route::post('/ipncoinpaybtc', 'PaymentController@ipnCoinPayBtc')->name('ipn.coinPay.btc');
Route::post('/ipncoinpayeth', 'PaymentController@ipnCoinPayEth')->name('ipn.coinPay.eth');
Route::post('/ipncoinpaybch', 'PaymentController@ipnCoinPayBch')->name('ipn.coinPay.bch');
Route::post('/ipncoinpaydash', 'PaymentController@ipnCoinPayDash')->name('ipn.coinPay.dash');
Route::post('/ipncoinpaydoge', 'PaymentController@ipnCoinPayDoge')->name('ipn.coinPay.doge');
Route::post('/ipncoinpayltc', 'PaymentController@ipnCoinPayLtc')->name('ipn.coinPay.ltc');
Route::post('/ipncoin', 'PaymentController@ipnCoin')->name('ipn.coinpay');
Route::post('/ipncoingate', 'PaymentController@ipnCoinGate')->name('ipn.coingate');


Route::post('/ipnpaytm', 'PaymentController@ipnPayTm')->name('ipn.paytm');
Route::post('/ipnpayeer', 'PaymentController@ipnPayEer')->name('ipn.payeer');
Route::post('/ipnpaystack', 'PaymentController@ipnPayStack')->name('ipn.paystack');
Route::post('/ipnvoguepay', 'PaymentController@ipnVoguePay')->name('ipn.voguepay');
//Payment IPN



Route::get('/', 'FrontendController@index')->name('main');

Route::get('/buy', 'FrontendController@buy')->name('buy');
Route::get('/sell', 'FrontendController@sell')->name('sell');


Route::get('/blogs', 'FrontendController@blog')->name('blog');
Route::get('/details/{id}/{slud}', 'FrontendController@details')->name('blog.details');
Route::get('/category/{id}/{slug}', 'FrontendController@categoryByBlog')->name('cats.blog');
Route::get('/about-us', 'FrontendController@about')->name('about');
Route::get('/service/{id}/{slug}', 'FrontendController@service')->name('serve');

Route::get('/faqs', 'FrontendController@faqs')->name('faqs');
Route::get('/terms-condition', 'FrontendController@termsCondition')->name('terms-condition');
Route::get('/privacy-policy', 'FrontendController@privacyPolicy')->name('privacy-policy');
Route::get('/menu/{id}/{slug}', 'FrontendController@menu')->name('menu');
Route::post('/subscribe', 'FrontendController@subscribe')->name('subscribe');
Route::get('/contact-us', 'FrontendController@contactUs')->name('contact-us');
Route::post('/contact-us','FrontendController@contactSubmit')->name('contact-us');

Auth::routes();

Route::group(['middleware' => ['guest']], function () {
    Route::get('/register/{reference}', 'FrontendController@register')->name('refer.register');
});


Route::group(['prefix' => 'user'], function () {

    Route::get('authorization', 'HomeController@authCheck')->name('user.authorization');
    Route::post('verification', 'HomeController@sendVcode')->name('user.send-vcode');
    Route::post('smsVerify', 'HomeController@smsVerify')->name('user.sms-verify');
    Route::post('verify-email', 'HomeController@sendEmailVcode')->name('user.send-emailVcode');
    Route::post('postEmailVerify', 'HomeController@postEmailVerify')->name('user.email-verify');


    Route::group(['middleware' => ['auth','CheckStatus']], function() {
        Route::get('/home', 'HomeController@index')->name('home');

        //user Deposit
        Route::get('/deposit', 'HomeController@deposit')->name('deposit');
        Route::post('/deposit', 'HomeController@deposit')->name('deposit');
        Route::post('/deposit-data-insert', 'HomeController@depositDataInsert')->name('deposit.data-insert');
        Route::get('/deposit-preview', 'HomeController@depositPreview')->name('user.deposit.preview');
        Route::post('/deposit-confirm', 'PaymentController@depositConfirm')->name('deposit.confirm');

        Route::get('/withdraw-money', 'HomeController@withdrawMoney')->name('withdraw.money');
        Route::post('/withdraw-preview', 'HomeController@requestPreview')->name('withdraw.preview');
        Route::post('/withdraw-submit', 'HomeController@requestSubmit')->name('withdraw.submit');

        Route::get('/transaction-log', 'HomeController@activity')->name('user.trx');
        Route::get('/deposit-log', 'HomeController@depositLog')->name('user.depositLog');
        Route::get('/withdraw-log', 'HomeController@withdrawLog')->name('user.withdrawLog');

        Route::get('change-password', 'HomeController@changePassword')->name('user.change-password');
        Route::post('change-password', 'HomeController@submitPassword')->name('user.change-password');
        Route::get('edit-profile', 'HomeController@editProfile')->name('edit-profile');
        Route::post('edit-profile', 'HomeController@submitProfile')->name('edit-profile');

        Route::post('buy','HomeController@buy')->name('buy.amount');
        Route::get('buy/{trx}','HomeController@buyPreview')->name('buy.buyPreview');
        Route::post('confirm-buy','HomeController@buyConfirm')->name('buy.confirmed');
        Route::post('confirm-buy-slip','HomeController@buyConfirmSlip')->name('buy.confirmed.slip');

        Route::post('sell','HomeController@sell')->name('sell.amount');
        Route::get('sell/{trx}','HomeController@sellPreview')->name('sell.preview');
        Route::post('confirm-sell','HomeController@sellConfirm')->name('sell.confirmed');
        Route::post('confirm-sell-bank','HomeController@sellConfirmBank')->name('sell.confirmed.bank');

        Route::post('exchange','HomeController@exchange')->name('exchange.amount');
        Route::get('exchange/{trx}','HomeController@exchangePreview')->name('exchange.preview');
        Route::post('confirm-exchange','HomeController@exchangeConfirm')->name('exchange.confirmed');

        Route::get('reference-bonus','HomeController@referenceBonus')->name('reference-bonus');
    });

});


Route::group(['prefix' => 'admin'], function () {
    Route::get('/', 'AdminLoginController@index')->name('admin.loginForm');
    Route::post('/', 'AdminLoginController@authenticate')->name('admin.login');
});


Route::group(['prefix' => 'admin', 'middleware' => 'auth:admin'], function () {



    Route::get('/dashboard', 'AdminController@dashboard')->name('admin.dashboard');
    

    Route::get('/exchange-log', 'AdminController@exchangeLog')->name('exchange-currency');
    Route::get('/exchange-log/{id}', 'AdminController@exchangeInfo')->name('exchange-info');
    Route::post('/exchange-action', 'AdminController@exchangeAction')->name('exchange-action');

    Route::get('/sell-log', 'AdminController@sellLog')->name('sell-currency');
    Route::get('/sell-log/{id}', 'AdminController@sellInfo')->name('sell-info');
    Route::post('/sell-action', 'AdminController@sellAction')->name('sell-action');

    Route::get('/buy-log', 'AdminController@buyLog')->name('buy-currency');
    Route::get('/buy-log/{id}', 'AdminController@buyInfo')->name('buy-info');
    Route::post('/buy-action', 'AdminController@buyAction')->name('buy-action');


    // General Settings
    Route::get('/general-settings', 'GeneralSettingController@GenSetting')->name('admin.GenSetting');
    Route::post('/general-settings', 'GeneralSettingController@UpdateGenSetting')->name('admin.UpdateGenSetting');

    //Contact Setting
    Route::get('contact-setting', 'GeneralSettingController@getContact')->name('contact-setting');
    Route::put('contact-setting/{id}', 'GeneralSettingController@putContactSetting')->name('contact-setting-update');


    // Admin Settings
    Route::get('/change-password', 'AdminController@changePassword')->name('admin.changePass');
    Route::post('/change-password', 'AdminController@updatePassword')->name('admin.changePass');
    Route::get('/profile', 'AdminController@profile')->name('admin.profile');
    Route::post('/profile', 'AdminController@updateProfile')->name('admin.profile');

    Route::resource('currency','CurrencyController');

    //Gateway
    Route::get('/gateway', 'GatewayController@show')->name('gateway');
    Route::post('/gateway', 'GatewayController@update')->name('update.gateway');

    //Deposit
    Route::get('/deposits', 'DepositController@index')->name('deposits');
    Route::get('/deposits/requests', 'DepositController@requests')->name('deposits.requests');
    Route::put('/deposit/approve/{id}', 'DepositController@approve')->name('deposit.approve');
    Route::get('/deposit/{deposit}/delete', 'DepositController@destroy')->name('deposit.destroy');

    //withdraw
    Route::get('/withdraw', 'WithdrawController@index')->name('withdraw');
    Route::post('/withdraw', 'WithdrawController@store')->name('add.withdraw.method');
    Route::post('/withdraw-update', 'WithdrawController@withdrawUpdateSettings')->name('update.wsettings');

    Route::get('/withdraw/requests', 'WithdrawController@requests')->name('withdraw.requests');
    Route::get('/withdraw/approved', 'WithdrawController@requestsApprove')->name('withdraw.approved');
    Route::get('/withdraw/refunded', 'WithdrawController@requestsRefunded')->name('withdraw.refunded');

    Route::put('/withdraw/approve/{id}', 'WithdrawController@approve')->name('withdraw.approve');

core/resources/views/admin/change_password.blade.php
@extends('admin')

@section('body')
    <div class="app-title">
        <div>
            <h1><i class="fa fa-key"></i> {{$page_title}}</h1>
        </div>
        <ul class="app-breadcrumb breadcrumb">
            <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
            <li class="breadcrumb-item"><a href="{{url()->current()}}">Password Settings</a></li>
        </ul>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="tile">
                <h3 class="tile-title">{{$page_title}}</h3>
                <div class="tile-body">
                    <form class="form-horizontal" role="form" action="" method="post">
                        @csrf
                        <div class="form-group{{ $errors->has('old_password') ? ' has-error' : '' }}">
                            <label class="col-md-3 offset-md-1 control-label"><h4>Current Password</h4></label>
                            <div class="col-md-9 offset-md-1">
                                <div class="input-group">
                                    <input type="password" name="old_password" class="form-control form-control-lg"
                                           placeholder="Current Password">
                                    <div class="input-group-append"><span class="input-group-text"><i
                                                    class="fa fa-lock"></i></span></div>
                                </div>
                                @if ($errors->has('old_password'))
                                    <strong class="error">{{ $errors->first('old_password') }}</strong>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('new_password') ? ' has-error' : '' }}">
                            <label class="col-md-3 offset-md-1 control-label"><h4>New Password</h4></label>
                            <div class="col-md-9 offset-md-1">
                                <div class="input-group">
                                    <input type="password" name="new_password" class="form-control form-control-lg"
                                           placeholder="New Password">
                                    <div class="input-group-append"><span class="input-group-text"><i
                                                    class="fa fa-lock"></i></span></div>
                                </div>
                                @if ($errors->has('new_password'))
                                    <strong class="error">{{ $errors->first('new_password') }}</strong>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('password_confirmation') ? ' has-error' : '' }}">
                            <label class="col-md-3 offset-md-1 control-label"><h4>Confirm Password</h4></label>
                            <div class="col-md-9 offset-md-1">
                                <div class="input-group">
                                    <input type="password" name="password_confirmation"
                                           class="form-control form-control-lg" placeholder="Confirm Password">
                                    <div class="input-group-append"><span class="input-group-text"><i
                                                    class="fa fa-lock"></i></span></div>
                                </div>
                                @if ($errors->has('password_confirmation'))
                                    <strong class="error">{{ $errors->first('password_confirmation') }}</strong>
                                @endif
                            </div>
                        </div>


                        <div class="form-group form-control-lg offset-md-1 col-md-9">
                            <button type="submit" class="btn btn-block btn-lg btn-primary">Submit</button>
                        </div>


                    </form>
                </div>
            </div>
        </div>
    </div>


@stop

core/resources/views/admin/dashboard.blade.php
@extends('admin')

@section('body')

    @php
        $totalusers = \App\User::count();
       $banusers = \App\User::where('status',0)->count();
       $verifiedPhone = \App\User::where('phone_verify',1)->count();
       $verifiedEmail = \App\User::where('email_verify',1)->count();
       $activeusers = \App\User::where('status',1)->count();

        $gateway =  App\Gateway::count();
        $deposit =  App\Deposit::whereStatus(1)->count();
        $totalDeposit =  App\Deposit::whereStatus(1)->sum('amount');

        $blog =App\Post::count();
        $subscribers =App\Subscriber::count();

    $currency =  App\Currency::count();
    $buycurrency =  App\BuyMoney::where('status','!=',0)->count();
    $sellcurrency =  App\SellMoney::where('status','!=',0)->count();
    $exchangecurrency =  App\ExchangeMoney::where('status','!=',0)->count();

    @endphp

    <div class="app-title">
        <div>
            <h1><i class="fa fa-dashboard"></i> {{$page_title}}</h1>
        </div>
        <ul class="app-breadcrumb breadcrumb">
            <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
            <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">Dashboard</a></li>
        </ul>
    </div>



    <div class="tile ">
        <h3 class="tile-title"><i class="fa fa-exchange"></i> Currency Statistics</h3>
        <div class="tile-body">
            <div class="row">

                <div class="col-lg-3 ">
                    <a href="{{route('currency.index')}}" class="text-decoration">
                        <div class="bs-component">
                            <div class="card mb-3 text-white  bg-success  text-center">
                                <div class="card-body">
                                    <blockquote class="card-blockquote">
                                        <h3>Manage Currency</h3>
                                        <h5>{{$currency}} </h5>
                                    </blockquote>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>

                <div class="col-lg-3">
                    <a href="{{route('buy-currency')}}" class="text-decoration">
                        <div class="bs-component">
                            <div class="card mb-3 text-white  bg-dark  text-center">
                                <div class="card-body">
                                    <blockquote class="card-blockquote">
                                        <h3>Buy Currency</h3>
                                        <h5>{{$buycurrency}} </h5>
                                    </blockquote>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-3">
                    <a href="{{route('sell-currency')}}" class="text-decoration">
                        <div class="bs-component">
                            <div class="card mb-3 text-white  bg-primary  text-center">
                                <div class="card-body">
                                    <blockquote class="card-blockquote">
                                        <h3>Sell Currency</h3>
                                        <h5>{{$sellcurrency}} </h5>
                                    </blockquote>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-3">
                    <a href="{{route('exchange-currency')}}" class="text-decoration">
                        <div class="bs-component">
                            <div class="card mb-3 text-white  bg-info  text-center">

                                <div class="card-body">
                                    <blockquote class="card-blockquote">
                                        <h3>Exchange Currency </h3>
                                        <h5>{{$exchangecurrency}} </h5>
                                    </blockquote>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>


    <div class="tile ">
        <h3 class="tile-title"><i class="fa fa-users"></i> User Statistics</h3>
        <div class="tile-body">
            <div class="row">

                <div class="col-lg-3 ">
                    <a href="{{route('users')}}" class="text-decoration">
                        <div class="bs-component">
                            <div class="card mb-3 text-white  bg-info  text-center">
                                <div class="card-body">
                                    <blockquote class="card-blockquote">
                                        <h3>Total Users</h3>
                                        <h5>{{$totalusers}} </h5>
                                    </blockquote>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>

                <div class="col-lg-3">
                    <a href="{{route('users')}}" class="text-decoration">
                        <div class="bs-component">
                            <div class="card mb-3 text-white  bg-success  text-center">
                                <div class="card-body">
                                    <blockquote class="card-blockquote">
                                        <h3>Email Verified Users</h3>
                                        <h5>{{$verifiedEmail}} </h5>
                                    </blockquote>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-3">
                    <a href="{{route('users')}}" class="text-decoration">
                        <div class="bs-component">
                            <div class="card mb-3 text-white  bg-dark  text-center">
                                <div class="card-body">
                                    <blockquote class="card-blockquote">
                                        <h3>Phone Verified Users</h3>
                                        <h5>{{$verifiedPhone}} </h5>
                                    </blockquote>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-3">
                    <a href="{{route('user.ban')}}" class="text-decoration">
                        <div class="bs-component">
                            <div class="card mb-3 text-white  bg-danger  text-center">

                                <div class="card-body">
                                    <blockquote class="card-blockquote">
                                        <h3>Ban Users </h3>
                                        <h5>{{$banusers}} </h5>
                                    </blockquote>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>




    <div class="row">
        <div class="col-md-6 ">
            <div class="tile">
                <h3 class="tile-title"><i class="fa fa-th"></i> Deposit Statistics</h3>
                <div class="tile-body">
                    <div class="row">

                        <div class="col-lg-6">
                            <a href="{{route('gateway')}}" class="text-decoration">
                                <div class="bs-component">
                                    <div class="card mb-3 text-white  bg-dark  text-center">

                                        <div class="card-body">
                                            <blockquote class="card-blockquote">
                                                <h3>Deposit Method</h3>
                                                <h5>{{$gateway}} </h5>
                                            </blockquote>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                        <div class="col-lg-6">
                            <a href="{{route('deposits')}}" class="text-decoration">
                                <div class="bs-component">
                                    <div class="card mb-3 text-white  bg-primary  text-center">
                                        <div class="card-body">
                                            <blockquote class="card-blockquote">
                                                <h3>Number Of Deposit </h3>
                                                <h5>{{$deposit}} </h5>
                                            </blockquote>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>

                </div>
            </div>
        </div>

        <div class="col-md-6 ">
                <div class="tile ">
                    <h3 class="tile-title"><i class="fa fa-th"></i> Other Info</h3>

                    <div class="tile-body">
                        <div class="row">

                            <div class="col-lg-6">
                                <a href="{{route('admin.blog')}}" class="text-decoration">
                                    <div class="bs-component">
                                        <div class="card mb-3  text-white  bg-dark  text-center">

                                            <div class="card-body">
                                                <blockquote class="card-blockquote">
                                                    <h3>Total Blogs</h3>
                                                    <h5>{{$blog}} </h5>
                                                </blockquote>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </div>

                            <div class="col-lg-6">
                                <a href="{{route('manage.subscribers')}}" class="text-decoration">
                                    <div class="bs-component">
                                        <div class="card mb-3 text-white  bg-primary  text-center">
                                            <div class="card-body">
                                                <blockquote class="card-blockquote">
                                                    <h3>Total Subscribers </h3>
                                                    <h5>{{$subscribers}} </h5>
                                                </blockquote>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
    </div>









@endsection

@section('script')


@stop

core/resources/views/admin/login.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="{{asset('assets/images/logo/favicon.png')}}" />
    <!-- Main CSS-->
    <link rel="stylesheet" type="text/css" href="{{asset('assets/admin/css/main.css')}}">
    <!-- Font-icon css-->
    <link rel="stylesheet" type="text/css" href="{{asset('assets/admin/css/font-awesome.min.css')}}">
    <link rel="stylesheet"  href="{{asset('assets/admin/css/custom.php')}}?color={{ $basic->color }}">
    <title>{{$page_title}} | {{$basic->sitename}}</title>
    <style>
        #error{
            color: red;
        }
        .error
        {
            color: red;
        }
        .abir{
            display: fixed;
            z-index: 299;
            position: absolute;
            /*width: 85%;*/
            color: #FFF;
            background-color: #26a1ab;
            border-color: #26a1ab;
        }
        .slow-spin {
            -webkit-animation: fa-spin 2s infinite linear;
            animation: fa-spin 2s infinite linear;
        }
    </style>
</head>
<body>
<section class="material-half-bg" style="background-color: #{{ $basic->color }};">
    {{--<div class="cover"></div>--}}
</section>

<section class="login-content">
    <div class="logo">
        <h1>{{$basic->sitename}}</h1>
    </div>
    <div class="login-box">
        <form class="login-form" id="login-form" action="" method="post">
            {{ csrf_field() }}
            <h3 class="login-head"><i class="fa fa-lg fa-fw fa-user"></i>SIGN IN</h3>
            <div class="form-group">
                <label class="control-label">USERNAME</label>
                <input class="form-control form-control-lg" name="username" type="text" placeholder="Username" autofocus>
            </div>
            <div class="form-group">
                <label class="control-label">PASSWORD</label>
                <input class="form-control form-control-lg" name="password" type="password" placeholder="Password">
            </div>

            <div class="form-group btn-container" id="working">
                <button class="btn btn-primary btn-block btn-lg" ><i class="fa fa-sign-in fa-lg fa-fw"></i>SIGN IN</button>
            </div>
            <br>
            <div id="error"></div>
        </form>

    </div>
</section>admin
<!-- Essential javascripts for application to work-->
<script src="{{asset('assets/admin/js/jquery-3.2.1.min.js')}}"></script>
<script src="{{asset('assets/admin/js/popper.min.js')}}"></script>
<script src="{{asset('assets/admin/js/bootstrap.min.js')}}"></script>
<script src="{{asset('assets/admin/js/jquery.validate.min.js')}}" type="text/javascript"></script>

<script src="{{asset('assets/admin/js/main.js')}}"></script>
<!-- The javascript plugin to display page loading on top-->
<script src="{{asset('assets/admin/js/pace.min.js')}}"></script>


<script>
    $('document').ready(function(){
        /* validation */
        $("#login-form").validate({
            rules:
                {
                    password: {
                        required: true,
                    },
                    username: {
                        required: true,
                    },
                },
            messages:
                {
                    password: "<span style='color: red'>Password is required.</span>",
                    username: "<span style='color: red'>Username is required.</span>",
                },
            submitHandler: submitForm
        });
        /* validation */

        /* login submit */
        function submitForm(){
            var data = $("#login-form").serialize();

            $.ajax({

                type : 'POST',
                url  : "{{route('admin.login')}}",
                data : data,
                beforeSend: function()
                {
                    $("#error").fadeOut();
                    $("#working").html('<button class="btn btn-primary btn-block btn-lg" >  <i class = "fa fa-spinner slow-spin"></i>  Validating Your Username ... </button>');
                },
                success :  function(response)
                {
                    if(response=="ok"){

                        $("#working").html('<button class="btn btn-primary btn-block btn-lg"> <i class="fa fa-check"></i> Success, Waiting to Dashboard ...</button>');
                        setTimeout(' window.location.href = "{{route('admin.dashboard')}}"; ',3000);
                    }
                    else{
                        $("#error").fadeIn(1000, function(){
                            $("#error").html('<div class="alert alert-dismissible alert-danger"><button class="close" type="button" data-dismiss="alert">×</button>'+response+'</div>');
                            $("#working").html('<button class="btn btn-primary btn-block btn-lg" id="working"><i class="fa fa-sign-in fa-lg fa-fw"></i>SIGN IN</button>');
                        });
                    }
                },
                error :  function(response)
                {
                    $("#error").fadeIn(1000, function(){
                        $("#error").html('<div class="alert alert-dismissible alert-danger"><button class="close" type="button" data-dismiss="alert">×</button>'+response+'</div>');
                        $("#working").html('');
                    });
                }
            });
            return false;
        }
        /* login submit */
    });
</script>
</body>
</html>