core/routes/admin.php
<?php

core/routes/web.php
    Route::post('smsVerify', 'HomeController@smsVerify')->name('user.sms-verify');
    Route::post('verify-email', 'HomeController@sendEmailVcode')->name('user.send-emailVcode');
    Route::post('postEmailVerify', 'HomeController@postEmailVerify')->name('user.email-verify');


    Route::group(['middleware' => ['auth','CheckStatus']], function() {
        Route::get('/home', 'HomeController@index')->name('home');

        //user Deposit
        Route::get('/deposit', 'HomeController@deposit')->name('deposit');
        Route::post('/deposit', 'HomeController@deposit')->name('deposit');
        Route::post('/deposit-data-insert', 'HomeController@depositDataInsert')->name('deposit.data-insert');
        Route::get('/deposit-preview', 'HomeController@depositPreview')->name('user.deposit.preview');
        Route::post('/deposit-confirm', 'PaymentController@depositConfirm')->name('deposit.confirm');

        Route::get('/withdraw-money', 'HomeController@withdrawMoney')->name('withdraw.money');
        Route::post('/withdraw-preview', 'HomeController@requestPreview')->name('withdraw.preview');
        Route::post('/withdraw-submit', 'HomeController@requestSubmit')->name('withdraw.submit');

        Route::get('/transaction-log', 'HomeController@activity')->name('user.trx');
        Route::get('/deposit-log', 'HomeController@depositLog')->name('user.depositLog');
        Route::get('/withdraw-log', 'HomeController@withdrawLog')->name('user.withdrawLog');

        Route::get('change-password', 'HomeController@changePassword')->name('user.change-password');
        Route::post('change-password', 'HomeController@submitPassword')->name('user.change-password');
        Route::get('edit-profile', 'HomeController@editProfile')->name('edit-profile');
        Route::post('edit-profile', 'HomeController@submitProfile')->name('edit-profile');

        Route::post('buy','HomeController@buy')->name('buy.amount');
        Route::get('buy/{trx}','HomeController@buyPreview')->name('buy.buyPreview');
        Route::post('confirm-buy','HomeController@buyConfirm')->name('buy.confirmed');
        Route::post('confirm-buy-slip','HomeController@buyConfirmSlip')->name('buy.confirmed.slip');

        Route::post('sell','HomeController@sell')->name('sell.amount');
        Route::get('sell/{trx}','HomeController@sellPreview')->name('sell.preview');
        Route::post('confirm-sell','HomeController@sellConfirm')->name('sell.confirmed');
        Route::post('confirm-sell-bank','HomeController@sellConfirmBank')->name('sell.confirmed.bank');

        Route::post('exchange','HomeController@exchange')->name('exchange.amount');
        Route::get('exchange/{trx}','HomeController@exchangePreview')->name('exchange.preview');
        Route::post('confirm-exchange','HomeController@exchangeConfirm')->name('exchange.confirmed');

        Route::get('reference-bonus','HomeController@referenceBonus')->name('reference-bonus');
    });

});


Route::group(['prefix' => 'admin'], function () {
    Route::get('/', 'AdminLoginController@index')->name('admin.loginForm');
    Route::post('/', 'AdminLoginController@authenticate')->name('admin.login');
});


Route::group(['prefix' => 'admin', 'middleware' => 'auth:admin'], function () {



    Route::get('/dashboard', 'AdminController@dashboard')->name('admin.dashboard');
    

    Route::get('/exchange-log', 'AdminController@exchangeLog')->name('exchange-currency');
    Route::get('/exchange-log/{id}', 'AdminController@exchangeInfo')->name('exchange-info');
    Route::post('/exchange-action', 'AdminController@exchangeAction')->name('exchange-action');

    Route::get('/sell-log', 'AdminController@sellLog')->name('sell-currency');
    Route::get('/sell-log/{id}', 'AdminController@sellInfo')->name('sell-info');
    Route::post('/sell-action', 'AdminController@sellAction')->name('sell-action');

    Route::get('/buy-log', 'AdminController@buyLog')->name('buy-currency');
    Route::get('/buy-log/{id}', 'AdminController@buyInfo')->name('buy-info');
    Route::post('/buy-action', 'AdminController@buyAction')->name('buy-action');


    // General Settings
    Route::get('/general-settings', 'GeneralSettingController@GenSetting')->name('admin.GenSetting');
    Route::post('/general-settings', 'GeneralSettingController@UpdateGenSetting')->name('admin.UpdateGenSetting');

    //Contact Setting
    Route::get('contact-setting', 'GeneralSettingController@getContact')->name('contact-setting');
    Route::put('contact-setting/{id}', 'GeneralSettingController@putContactSetting')->name('contact-setting-update');


    // Admin Settings
    Route::get('/change-password', 'AdminController@changePassword')->name('admin.changePass');
    Route::post('/change-password', 'AdminController@updatePassword')->name('admin.changePass');
    Route::get('/profile', 'AdminController@profile')->name('admin.profile');
    Route::post('/profile', 'AdminController@updateProfile')->name('admin.profile');

    Route::resource('currency','CurrencyController');

    //Gateway
    Route::get('/gateway', 'GatewayController@show')->name('gateway');
    Route::post('/gateway', 'GatewayController@update')->name('update.gateway');

    //Deposit
    Route::get('/deposits', 'DepositController@index')->name('deposits');
    Route::get('/deposits/requests', 'DepositController@requests')->name('deposits.requests');
    Route::put('/deposit/approve/{id}', 'DepositController@approve')->name('deposit.approve');
    Route::get('/deposit/{deposit}/delete', 'DepositController@destroy')->name('deposit.destroy');

    //withdraw
    Route::get('/withdraw', 'WithdrawController@index')->name('withdraw');
    Route::post('/withdraw', 'WithdrawController@store')->name('add.withdraw.method');
    Route::post('/withdraw-update', 'WithdrawController@withdrawUpdateSettings')->name('update.wsettings');

    Route::get('/withdraw/requests', 'WithdrawController@requests')->name('withdraw.requests');
    Route::get('/withdraw/approved', 'WithdrawController@requestsApprove')->name('withdraw.approved');
    Route::get('/withdraw/refunded', 'WithdrawController@requestsRefunded')->name('withdraw.refunded');

    Route::put('/withdraw/approve/{id}', 'WithdrawController@approve')->name('withdraw.approve');
    Route::post('/withdraw/refund', 'WithdrawController@refundAmount')->name('withdraw.refund');


    //    Blog Controller
    Route::get('/blog-category', 'PostController@category')->name('admin.cat');
    Route::post('/blog-category', 'PostController@UpdateCategory')->name('update.cat');
    Route::get('blog', 'PostController@index')->name('admin.blog');
    Route::get('blog/create', 'PostController@create')->name('blog.create');
    Route::post('blog/create', 'PostController@store')->name('blog.store');
    Route::delete('blog/delete', 'PostController@destroy')->name('blog.delete');
    Route::get('blog/edit/{id}', 'PostController@edit')->name('blog.edit');
    Route::post('blog-update', 'PostController@updatePost')->name('blog.update');

    /*Manage Faq*/
    Route::get('faqs-create', 'FaqController@createFaqs')->name('faqs-create');
    Route::post('faqs-create', 'FaqController@storeFaqs')->name('faqs-create');
    Route::get('faqs', 'FaqController@allFaqs')->name('faqs-all');
    Route::get('faqs-edit/{id}', 'FaqController@editFaqs')->name('faqs-edit');
    Route::put('faqs-edit/{id}', 'FaqController@updateFaqs')->name('faqs-update');
    Route::delete('faqs-delete', 'FaqController@deleteFaqs')->name('faqs-delete');

    //    SubscriberController
    Route::get('/subscribers', 'SubscriberController@manageSubscribers')->name('manage.subscribers');
    Route::post('/update-subscribers', 'SubscriberController@updateSubscriber')->name('update.subscriber');
    Route::get('/send-email', 'SubscriberController@sendMail')->name('send.mail.subscriber');
    Route::post('/send-email', 'SubscriberController@sendMailsubscriber')->name('send.email.subscriber');

    //    Testimonial Controller
    Route::get('testimonial', 'TestimonialController@index')->name('admin.testimonial');
    Route::get('testimonial/create', 'TestimonialController@create')->name('testimonial.create');
    Route::post('testimonial/create', 'TestimonialController@store')->name('testimonial.store');
    Route::delete('testimonial/delete', 'TestimonialController@destroy')->name('testimonial.delete');
    Route::get('testimonial/edit/{id}', 'TestimonialController@edit')->name('testimonial.edit');
    Route::post('testimonial-update', 'TestimonialController@updatePost')->name('testimonial.update');

    //User Management
    Route::get('users', 'UserManageController@users')->name('users');
    Route::get('user-search', 'UserManageController@userSearch')->name('search.users');
    Route::get('user/{user}', 'UserManageController@singleUser')->name('user.single');
    Route::put('user/pass-change/{user}', 'UserManageController@userPasschange')->name('user.passchange');
    Route::put('user/status/{user}', 'UserManageController@statupdate')->name('user.status');
    Route::get('mail/{user}', 'UserManageController@userEmail')->name('user.email');
    Route::post('/sendmail', 'UserManageController@sendemail')->name('send.email');
    Route::get('/user-login-history/{id}', 'UserManageController@loginLogsByUsers')->name('user.login.history');
    Route::get('/user-balance/{id}', 'UserManageController@ManageBalanceByUsers')->name('user.balance');
    Route::post('/user-balance', 'UserManageController@saveBalanceByUsers')->name('user.balance.update');
    Route::get('/user-banned', 'UserManageController@banusers')->name('user.ban');
    Route::get('login-logs/{user?}', 'UserManageController@loginLogs')->name('user.login-logs');
    Route::get('/user-transaction/{id}', 'UserManageController@userTrans')->name('user.trans');
    Route::get('/user-deposit/{id}', 'UserManageController@userDeposit')->name('user.deposit');
    Route::get('/user-withdraw/{id}', 'UserManageController@userWithdraw')->name('user.withdraw');

core/app/Currency.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Currency extends Model
{
    protected $guarded = [];
    protected $table = "currencies";
}

core/app/Http/Controllers/CurrencyController.php
<?php

namespace App\Http\Controllers;

use App\Currency;
use Illuminate\Http\Request;
use Auth;
use App\GeneralSettings;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Hash;
use File;
use Image;

class CurrencyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['page_title'] = 'Manage Currency';
        $data['currency'] = Currency::latest()->paginate(25);
        return view('admin.currency.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['page_title'] = 'Manage Currency';
        return view('admin.currency.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'buy' => 'required|min:0',
            'sell' => 'required|min:0',
            'exchange' => 'required|min:0',
            'price' => 'required|numeric|min:0',
            'available_balance' => 'required|numeric|min:0',
            'symbol' => 'required',
            'payment_id' => 'required',
            'name' => 'required',
            'image' => 'required|mimes:png,jpg,jpeg'
        ]);
        $in = Input::except('_method', '_token');
        $in['is_coin'] = $request->is_coin == "on" ? 1 : 0;
        $in['status'] = $request->status == "on" ? 1 : 0;

        if ($request->hasFile('image')) {
            $image = $request->file('image');
            $filename = str_slug($request->name) . '_' . time() . '.'.$image->getClientOriginalExtension();;
            $location = 'assets/images/currency/' . $filename;
            Image::make($image)->resize(32, 21)->save($location);
            $in['image'] = $filename;
        }
        Currency::create($in);
        return back()->with('success', 'Save Successfully!');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Currency $currency
     * @return \Illuminate\Http\Response
     */
    public function show(Currency $currency)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Currency $currency
     * @return \Illuminate\Http\Response
     */
    public function edit(Currency $currency)
    {
        $data['currency'] = $currency;
        $data['page_title'] = "Manage Currency";
        return view('admin.currency.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Currency $currency
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Currency $currency)
    {

        $request->validate([
            'buy' => 'required|min:0',
            'payment_id' => 'required',
            'sell' => 'required|min:0',
            'exchange' => 'required|min:0',
            'price' => 'required|numeric|min:0',
            'available_balance' => 'required|numeric|min:0',
            'symbol' => 'required',
            'name' => 'required',
            'image' => 'nullable|mimes:png,jpg,jpeg'
        ]);
        $in = Input::except('_method', '_token');
        $in['is_coin'] = $request->is_coin == "on" ? 1 : 0;
        $in['status'] = $request->status == "on" ? 1 : 0;

        if ($request->hasFile('image')) {
            $image = $request->file('image');
            $filename = str_slug($request->name).'_' . time() .'.'. $image->getClientOriginalExtension();
            $location = 'assets/images/currency/' . $filename;
            Image::make($image)->resize(32, 21)->save($location);
            $path = './assets/images/currency/';
            File::delete($path . $currency->image);
            $in['image'] = $filename;
        }

        $currency->fill($in)->save();

        return back()->with('success', 'Updated Successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Currency $currency
     * @return \Illuminate\Http\Response
     */
    public function destroy(Currency $currency)
    {
        //
    }
}

core/resources/views/admin/currency/buy-list.blade.php
@extends('admin')

@section('body')
    <div class="app-title">
        <div>
            <h1><i class="fa fa-exchange"></i> {{$page_title}}</h1>
        </div>
        <ul class="app-breadcrumb breadcrumb">
            <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
            <li class="breadcrumb-item"><a href="{{url()->current()}}">{{$page_title}}</a></li>
        </ul>
    </div>




    <div class="row">
        <div class="col-md-12">
            <div class="tile">
                <div class="tile-title "><i class="fa fa-exchange"></i>
                    {{$page_title}}
                </div>
                <div class="tile-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>Date</th>
                                <th>Send Amount </th>
                                <th>Get Currency</th>
                                <th> Buyer Name</th>
                                <th> Buyer Email</th>
                                <th style="width: 5%">Status</th>
                                <th>Action</th>
                            </tr>
                            </thead>

                            <tbody>

                            @foreach($exchange as $k=>$data)
                                <tr>
                                    <td data-label="Date">
                                        <strong>{{date('d M Y',strtotime($data->created_at))}}</strong>
                                    </td>
                                    <td data-label="Send Amount">
                                        <strong>{{number_format($data->enter_amount, $basic->decimal)}} {{$basic->currency}}</strong>
                                    </td>
                                    <td data-label="Get Currency">
                                        <strong>{{$data->get_amount}} {{$data->currency->symbol}}</strong>
                                    </td>

                                    <td data-label="Seller   Name">
                                        <a href="{{route('user.single',$data->user_id)}}">{{$data->user->username}}</a>
                                    </td>
                                    <td data-label="Seller Email">{{$data->user->email}}</td>

                                    <td data-label="Status">
                                        @if( $data->status ==2 )
                                            <span class="badge badge-success">Success</span>
                                        @elseif( $data->status == -2 )
                                            <span class="badge badge-danger">Rejected</span>
                                        @else
                                            <span class="badge badge-warning">Pending</span>
                                        @endif
                                    </td>
                                    <td data-label="Action">
                                        <a href="{{route('buy-info',$data->id)}}"
                                           class="btn btn-outline-info btn-sm ">
                                            <i class="fa fa-eye"></i> View
                                        </a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    {!! $exchange->render() !!}


                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
@endsection

core/resources/views/admin/currency/create.blade.php
@extends('admin')
@section('import-css')
    <link href="{{ asset('assets/admin/css/bootstrap-fileinput.css') }}" rel="stylesheet">
@stop
@section('body')
    <div class="app-title">
        <div>
            <h1><i class="fa fa-exchange"></i> {{$page_title}}</h1>
        </div>
        <ul class="app-breadcrumb breadcrumb">
            <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
            <li class="breadcrumb-item"><a href="{{url()->current()}}">{{$page_title}}</a></li>
        </ul>
    </div>


    <div class="row">
        <div class="col-md-12">
            <div class="tile">
                <h3 class="tile-title ">Add Currency
                    <a href="{{route('currency.index')}}" class="btn btn-success btn-md pull-right ">
                        <i class="fa fa-eye"></i> All Currency
                    </a>
                </h3><br>


                <div class="tile-body">
                    <div class="row">
                        <div class="col-md-8 offset-md-2">
                            <form role="form" method="POST" action="{{route('currency.store')}}" name="editForm" enctype="multipart/form-data">
                                {{ csrf_field() }}

                                <div class="row">
                                    <div class="form-group col-md-6">
                                        <h5>Currency  Name:</h5>
                                        <div class="input-group">
                                            <input type="text" class="form-control form-control-lg" placeholder="Currency  Name" value="{{old('name')}}"
                                                   name="name">
                                            <div class="input-group-append"><span class="input-group-text">
                                            <i class="fa fa-globe"></i>
                                            </span>
                                            </div>
                                        </div>
                                        @if ($errors->has('name'))
                                            <div class="error">{{ $errors->first('name') }}</div>
                                        @endif
                                    </div>
                                    <div class="form-group col-md-6">
                                        <h5> Currency 	Symbol:</h5>
                                        <input type="text" class="form-control form-control-lg" placeholder="Currency Symbol" value="{{old('symbol')}}"
                                               name="symbol">
                                        @if ($errors->has('symbol'))
                                            <div class="error">{{ $errors->first('symbol') }}</div>
                                        @endif

                                    </div>

                                </div>
                                <div class="row">

                                    <div class="form-group col-md-6">
                                        <h5>Price:</h5>
                                        <div class="input-group">
                                            <div class="input-group-append">
                                                <span class="input-group-text"><strong> 1 = {{$basic->currency}}</strong></span>
                                            </div>
                                            <input type="text" name="price"  value="{{old('price')}}" class="form-control form-control-lg"
                                                   onkeyup="this.value = this.value.replace (/^\.|[^\d\.]/g, '')">
                                        </div>
                                        @if ($errors->has('price'))
                                            <div class="error">{{ $errors->first('price') }}</div>
                                        @endif
                                    </div>

                                    <div class="form-group col-md-6">
                                        <h5> Available Balance </h5>
                                        <div class="input-group">
                                            <input type="text" name="available_balance" value="{{old('available_balance')}}" class="form-control form-control-lg"
                                                   placeholder="0.00" onkeyup="this.value = this.value.replace (/^\.|[^\d\.]/g, '')">
                                            <div class="input-group-append">
                                                <span class="input-group-text"><strong>Amount</strong></span>
                                            </div>
                                        </div>
                                        @if ($errors->has('available_balance'))
                                            <div class="error">{{ $errors->first('available_balance') }}</div>
                                        @endif
                                    </div>



                                    <div class="form-group col-md-6">
                                        <h5> Payment ID</h5>
                                            <input type="text" name="payment_id"  value="{{old('payment_id')}}" name="payment_id" class="form-control form-control-lg"
                                                   placeholder="Payment Id" >
                                        @if ($errors->has('payment_id'))
                                            <div class="error">{{ $errors->first('payment_id') }}</div>
                                        @endif
                                    </div>


                                        <div class="form-group col-md-6">
                                            <h5> Exchange Charge(%)</h5>
                                            <div class="input-group">
                                                <input type="text" name="exchange"  value="{{old('exchange')}}" name="exchange" class="form-control form-control-lg"
                                                       placeholder="0.00" onkeyup="this.value = this.value.replace (/^\.|[^\d\.]/g, '')">
                                                <div class="input-group-append">
                                                    <span class="input-group-text"><strong>%</strong></span>
                                                </div>
                                            </div>
                                            @if ($errors->has('exchange'))
                                                <div class="error">{{ $errors->first('exchange') }}</div>
                                            @endif
                                        </div>




                                    <div class="form-group col-md-6">
                                        <h5> Buying Charge(%)</h5>
                                        <div class="input-group">
                                            <input type="text" name="buy" value="{{old('buy')}}" class="form-control form-control-lg"
                                                   placeholder="0.00" onkeyup="this.value = this.value.replace (/^\.|[^\d\.]/g, '')">
                                            <div class="input-group-append">
                                                <span class="input-group-text"><strong>%</strong></span>
                                            </div>
                                        </div>
                                        @if ($errors->has('buy'))
                                            <div class="error">{{ $errors->first('buy') }}</div>
                                        @endif
                                    </div>

                                    <div class="form-group col-md-6">
                                        <h5> Selling Charge(%)</h5>
                                        <div class="input-group">
                                            <input type="text" name="sell"  value="{{old('sell')}}" class="form-control form-control-lg"
                                                   placeholder="0.00" onkeyup="this.value = this.value.replace (/^\.|[^\d\.]/g, '')">

                                            <div class="input-group-append">
                                                <span class="input-group-text"><strong>%</strong></span>
                                            </div>
                                        </div>
                                        @if ($errors->has('sell'))
                                            <div class="error">{{ $errors->first('sell') }}</div>
                                        @endif
                                    </div>
                                </div>



                                <div class="row">
                                    <div class=" col-md-6">
                                            <div class="form-group ">
                                                <h5>Is Coin ? </h5>
                                                <input data-toggle="toggle" data-size="large" data-onstyle="success" data-on="Yes" data-off="No"
                                                       data-offstyle="danger" data-width="100%" type="checkbox" name="is_coin">
                                            </div>

                                            <div class="form-group">
                                                <h5>Status:</h5>
                                                <input data-toggle="toggle" data-size="large" data-onstyle="success"
                                                       data-offstyle="danger" data-width="100%" type="checkbox" name="status">
                                            </div>

                                    </div>
                                    <div class=" col-md-6">
                                        <div class="form-group ">
                                            <h5>Image</h5>
                                            <div class="fileinput fileinput-new" data-provides="fileinput">
                                                <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;"
                                                     data-trigger="fileinput">
                                                    <img style="width: 200px"
                                                         src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text= Image"
                                                         alt="...">

                                                </div>
                                                <div class="fileinput-preview fileinput-exists thumbnail"
                                                     style="max-width: 200px; max-height: 150px"></div>
                                                <div>
                                                <span class="btn btn-info btn-file">
                                                    <span class="fileinput-new bold uppercase"><i
                                                            class="fa fa-file-image-o"></i> Select image</span>
                                                    <span class="fileinput-exists bold uppercase"><i
                                                            class="fa fa-edit"></i> Change</span>
                                                    <input type="file" name="image" accept="image/*">
                                                </span>
                                                    <a href="#" class="btn btn-danger fileinput-exists bold uppercase"
                                                       data-dismiss="fileinput"><i class="fa fa-trash"></i> Remove</a>
                                                </div>
                                            </div>
                                            @if ($errors->has('image'))
                                                <div class="error">{{ $errors->first('image') }}</div>
                                            @endif

                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="form-group col-md-12 ">
                                        <button class="btn btn-primary btn-block btn-lg">Save</button>
                                    </div>
                                </div>
                            </form>

                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection

@section('import-script')
    <script src="{{ asset('assets/admin/js/bootstrap-fileinput.js') }}"></script>
@stop
@section('script')
    <script src="{{ asset('assets/admin/js/nicEdit-latest.js') }}"></script>

    <script>
        bkLib.onDomLoaded(function () {
            new nicEditor({fullPanel: true}).panelInstance('area1');
        });
    </script>
@stop